# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec file for the FastAPI sidecar server."""

import sys
import os

block_cipher = None

a = Analysis(
    ['run_server.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('alembic/', 'alembic/'),
        ('alembic.ini', '.'),
        ('app/templates/', 'app/templates/'),
    ],
    hiddenimports=[
        # uvicorn internals
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.protocols.websockets.websockets_impl',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        # app package and submodules
        'app',
        'app.main',
        'app.config',
        'app.config_desktop',
        'app.database',
        'app.models',
        'app.models.project',
        'app.models.paper',
        'app.models.paper_chunk',
        'app.models.evidence_span',
        'app.models.research_idea',
        'app.models.experiment_plan',
        'app.models.experiment_result',
        'app.models.method_version',
        'app.models.reviewer_simulation',
        'app.models.manuscript_section',
        'app.models.manuscript_state',
        'app.models.citation',
        'app.models.section_citation',
        'app.models.export_template',
        'app.models.export_record',
        'app.models.paper_card',
        'app.schemas',
        'app.schemas.project',
        'app.schemas.paper',
        'app.schemas.paper_chunk',
        'app.schemas.evidence_span',
        'app.schemas.research_idea',
        'app.schemas.experiment_plan',
        'app.schemas.experiment_result',
        'app.schemas.method_version',
        'app.schemas.reviewer_simulation',
        'app.schemas.manuscript',
        'app.schemas.manuscript_section',
        'app.schemas.citation',
        'app.schemas.export_template',
        'app.schemas.export_record',
        'app.schemas.cover_letter',
        'app.schemas.response_letter',
        'app.schemas.export_request',
        'app.schemas.paper_card',
        'app.routers',
        'app.routers.projects',
        'app.routers.papers',
        'app.routers.ideas',
        'app.routers.experiments',
        'app.routers.manuscript',
        'app.routers.chunks',
        'app.routers.method_versions',
        'app.routers.experiment_results',
        'app.routers.reviewer',
        'app.routers.sections',
        'app.routers.citations',
        'app.routers.templates',
        'app.routers.export',
        'app.routers.converter',
        'app.routers.settings',
        'app.routers.backup',
        'app.services',
        'app.services.paper_analysis',
        'app.services.idea_generation',
        'app.services.experiment_planning',
        'app.services.manuscript_service',
        'app.services.evidence_service',
        'app.services.method_version_service',
        'app.services.results_analysis',
        'app.services.reviewer_service',
        'app.services.differentiation_service',
        'app.services.pdf_parsing',
        'app.services.citation_service',
        'app.services.template_service',
        'app.services.cover_letter_service',
        'app.services.response_letter_service',
        'app.services.docx_generator',
        'app.services.latex_generator',
        'app.services.word_to_latex_converter',
        'app.services.llm_service',
        'app.parsers',
        'app.parsers.base',
        'app.parsers.mock_parser',
        'app.parsers.pymupdf_parser',
        'app.parsers.experiment_result_parser',
        'app.parsers.bibtex_parser',
        'app.storage',
        'app.storage.base',
        'app.storage.local_storage',
        'app.compliance',
        'app.compliance.rules',
        'app.compliance.checker',
        'app.export',
        'app.export.pre_export_validator',
        # third-party
        'pymupdf',
        'fitz',
        'alembic.config',
        'alembic.command',
        'alembic.script',
        'alembic.runtime.migration',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.ext.asyncio',
        'jinja2',
        'docx',
        'openai',
        'httpx',
        'pydantic_settings',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'multipart',
        'starlette.middleware',
        'starlette.responses',
        'starlette.routing',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pytest',
        'pytest_asyncio',
        'tkinter',
        'matplotlib',
        'scipy',
        'numpy.testing',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='fastapi-server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
