"""
Compliance checker module.

Validates experiment plans, manuscript drafts, and other generated content
against academic integrity rules:
- Detects suspicious fabricated numerical claims in experiment plans.
- Rejects content that attributes authorship to AI / LLM systems.
- Returns structured pass/fail results with detailed violation messages.
"""

import re
from typing import Any


# Keywords that indicate an LLM is claiming authorship
_LLM_IDENTITY_KEYWORDS: list[str] = [
    "chatgpt",
    "gpt-4",
    "gpt-3",
    "gpt4",
    "gpt3",
    "claude",
    "copilot",
    "deepseek",
    "language model",
    "llm",
    "ai assistant",
    "ai as author",
    "ai-generated",
    "ai generated",
    "artificial intelligence generated",
]

# Suspicious numeric patterns often found in fabricated results
_NUMERIC_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (
        re.compile(r"\bachiev(?:ed|es|e)\s+(\d+\.?\d*)\s*%", re.IGNORECASE),
        "Achieved-percentage claim",
    ),
    (
        re.compile(r"\bimprovement\s+of\s+(\d+\.?\d*)\s*%", re.IGNORECASE),
        "Improvement-percentage claim",
    ),
    (
        re.compile(r"\bp[- ]?value\s*[<>=]\s*[\d.]+", re.IGNORECASE),
        "p-value claim",
    ),
    (
        re.compile(r"\boutperform\w*\s+.*?(\d+\.?\d*)\s*%\s*(accuracy|precision|recall|f1)", re.IGNORECASE),
        "Outperform-with-percentage claim",
    ),
]


def check_fake_numbers(content: str) -> list[str]:
    """
    Scan text for suspicious numeric patterns that may indicate fabricated results.

    Returns a list of violation description strings. An empty list means no issues found.
    """
    violations: list[str] = []

    for pattern, label in _NUMERIC_PATTERNS:
        matches = pattern.findall(content)
        if matches:
            violations.append(
                f"Suspicious numeric claim detected ({label}): "
                f"possible fabricated statistics ({len(matches)} occurrence(s))"
            )

    # Heuristic: flag text with an unusually high density of percentage claims
    percent_matches = re.findall(r"\b(\d+\.?\d*)\s*%", content)
    word_count = len(content.split())
    if len(percent_matches) > 5 and word_count > 0:
        ratio = len(percent_matches) / word_count
        if ratio > 0.05:
            violations.append(
                f"Unusually high density of percentage claims ({len(percent_matches)} in "
                f"{word_count} words), suggesting potentially fabricated statistics"
            )

    return violations


def check_ai_authorship(content: str) -> list[str]:
    """
    Scan text for claims that attribute authorship to an AI or language model.

    Uses both keyword-proximity patterns and direct phrase matching to detect
    a wide range of AI authorship claims.
    """
    violations: list[str] = []
    lower_content = content.lower()

    # --- Direct phrase patterns (most common real-world cases) ---
    direct_patterns: list[tuple[re.Pattern[str], str]] = [
        (re.compile(r"\bwritten\s+by\s+(chatgpt|gpt[- ]?4|gpt[- ]?3|claude|copilot|deepseek|ai|an?\s+ai|an?\s+llm|a\s+language\s+model|artificial\s+intelligence)", re.IGNORECASE),
         "written by"),
        (re.compile(r"\bauthored\s+by\s+(chatgpt|gpt[- ]?4|gpt[- ]?3|claude|copilot|deepseek|ai|an?\s+ai|an?\s+llm|a\s+language\s+model|artificial\s+intelligence)", re.IGNORECASE),
         "authored by"),
        (re.compile(r"\bgenerated\s+by\s+(chatgpt|gpt[- ]?4|gpt[- ]?3|claude|copilot|deepseek|ai|an?\s+ai|an?\s+llm|a\s+language\s+model|artificial\s+intelligence)", re.IGNORECASE),
         "generated by"),
    ]
    for pat, desc in direct_patterns:
        match = pat.search(content)
        if match:
            violations.append(
                f"AI authorship claim detected ({desc} {match.group(1).strip()}): "
                "content attributes authorship to an AI system, which violates academic integrity guidelines"
            )

    # --- Keyword + authorship-word proximity patterns ---
    authorship_words = r"(?:author|co-author|coauthor|contributor|writer)"
    for keyword in _LLM_IDENTITY_KEYWORDS:
        proximity_patterns = [
            re.compile(
                rf"{re.escape(keyword)}\s+(?:as\s+)?{authorship_words}",
                re.IGNORECASE,
            ),
            re.compile(
                rf"{authorship_words}\b.*?\b(?:is|was|by)\s+.*?{re.escape(keyword)}",
                re.IGNORECASE,
            ),
        ]
        for pat in proximity_patterns:
            if pat.search(content):
                violations.append(
                    f"AI authorship claim detected: content attributes authorship to "
                    f"'{keyword}', which violates academic integrity guidelines"
                )
                break

    return violations


def check_experiment_plan(plan_data: dict[str, Any]) -> dict[str, Any]:
    """
    Validate an experiment plan dict for compliance issues.

    Checks the text of every field (including nested experiment lists) for
    fabricated numeric claims.
    """
    violations: list[str] = []

    # Collect all textual content from the plan
    text_fragments: list[str] = []
    for key, value in plan_data.items():
        if isinstance(value, str):
            text_fragments.append(value)
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, dict):
                    for sub_value in item.values():
                        if isinstance(sub_value, str):
                            text_fragments.append(sub_value)
                elif isinstance(item, str):
                    text_fragments.append(item)

    full_text = " ".join(text_fragments)

    number_violations = check_fake_numbers(full_text)
    violations.extend(number_violations)

    authorship_violations = check_ai_authorship(full_text)
    violations.extend(authorship_violations)

    passed = len(violations) == 0
    return {
        "passed": passed,
        "status": "passed" if passed else "failed",
        "violations": violations,
    }


def check_manuscript(manuscript_data: dict[str, Any]) -> dict[str, Any]:
    """
    Validate manuscript content for compliance issues.

    Checks both the draft text and outline sections for AI authorship claims
    and fabricated numeric claims.
    """
    violations: list[str] = []

    draft = manuscript_data.get("current_draft", "")
    violations.extend(check_ai_authorship(draft))
    violations.extend(check_fake_numbers(draft))

    # Also check outline content
    outline = manuscript_data.get("outline", [])
    if isinstance(outline, list):
        for section in outline:
            if isinstance(section, dict):
                section_text = " ".join(
                    str(v) for v in section.values() if isinstance(v, (str, list))
                )
                if isinstance(section.get("key_points"), list):
                    section_text += " " + " ".join(
                        str(p) for p in section["key_points"] if isinstance(p, str)
                    )
                violations.extend(check_ai_authorship(section_text))
                violations.extend(check_fake_numbers(section_text))

    passed = len(violations) == 0
    return {
        "passed": passed,
        "status": "passed" if passed else "failed",
        "violations": violations,
    }


def run_compliance_check(content: dict[str, Any]) -> dict[str, Any]:
    """
    General-purpose compliance checker that auto-detects the content type.

    Accepts a dict that may represent an experiment plan or a manuscript state,
    and runs the appropriate validation.
    """
    all_violations: list[str] = []

    # If it looks like a manuscript (has current_draft or outline keys), check as manuscript
    if "current_draft" in content or "outline" in content:
        result = check_manuscript(content)
        all_violations.extend(result["violations"])

    # If it looks like an experiment plan (has main_experiments key), check as experiment plan
    if "main_experiments" in content:
        result = check_experiment_plan(content)
        all_violations.extend(result["violations"])

    # Fallback: if neither specific structure was detected, check raw text fields
    if "current_draft" not in content and "outline" not in content and "main_experiments" not in content:
        full_text = " ".join(str(v) for v in content.values() if isinstance(v, str))
        all_violations.extend(check_fake_numbers(full_text))
        all_violations.extend(check_ai_authorship(full_text))

    passed = len(all_violations) == 0
    return {
        "passed": passed,
        "status": "passed" if passed else "failed",
        "violations": all_violations,
    }


def check_results_without_data(analysis_data: dict[str, Any], has_raw_data: bool) -> dict[str, Any]:
    """
    Check whether an analysis contains numeric claims when no raw data was provided.

    If has_raw_data is False and the analysis text contains numeric claims
    (detected via regex), flag as non-compliant.

    Returns {passed: bool, status: str, violations: list[str]}.
    """
    violations: list[str] = []

    if not has_raw_data:
        # Collect all text from the analysis data
        text_fragments: list[str] = []
        for key, value in analysis_data.items():
            if isinstance(value, str):
                text_fragments.append(value)
            elif isinstance(value, list):
                for item in value:
                    if isinstance(item, str):
                        text_fragments.append(item)
                    elif isinstance(item, (int, float)):
                        text_fragments.append(str(item))
                    elif isinstance(item, list):
                        for sub_item in item:
                            if isinstance(sub_item, str):
                                text_fragments.append(sub_item)

        full_text = " ".join(text_fragments)

        # Check for numeric claims using the same patterns as check_fake_numbers
        number_violations = check_fake_numbers(full_text)
        for v in number_violations:
            violations.append(
                f"Analysis without raw data contains numeric claims: {v}"
            )

        # Also check with a general numeric pattern
        general_numbers = re.findall(r"\b\d+\.?\d*\s*%", full_text)
        if general_numbers and not number_violations:
            violations.append(
                f"Analysis generated without raw data contains {len(general_numbers)} "
                f"percentage value(s), which may be fabricated without supporting data"
            )

    passed = len(violations) == 0
    return {
        "passed": passed,
        "status": "passed" if passed else "failed",
        "violations": violations,
    }


def check_result_values_match_data(analysis_data: dict[str, Any], raw_data: list[dict]) -> dict[str, Any]:
    """
    Extract all numeric values mentioned in analysis text and check if they
    appear in raw_data values. Flag values that don't match.

    Returns {passed: bool, status: str, violations: list[str]}.
    """
    violations: list[str] = []

    if not raw_data:
        return {
            "passed": True,
            "status": "passed",
            "violations": [],
        }

    # Collect all text from analysis
    text_fragments: list[str] = []
    for key, value in analysis_data.items():
        if isinstance(value, str):
            text_fragments.append(value)
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, str):
                    text_fragments.append(item)
                elif isinstance(item, list):
                    for sub_item in item:
                        if isinstance(sub_item, str):
                            text_fragments.append(sub_item)

    full_text = " ".join(text_fragments)

    # Extract all numeric values from the analysis text
    mentioned_values = set()
    # Match standalone numbers (integers and floats)
    for match in re.findall(r"\b(\d+\.?\d*)\b", full_text):
        try:
            mentioned_values.add(float(match))
        except ValueError:
            pass

    # Collect all numeric values from raw_data
    data_values = set()
    for row in raw_data:
        for val in row.values():
            if isinstance(val, (int, float)):
                data_values.add(float(val))
            elif isinstance(val, str):
                for num_match in re.findall(r"\b(\d+\.?\d*)\b", val):
                    try:
                        data_values.add(float(num_match))
                    except ValueError:
                        pass

    # Check which mentioned values don't appear in the data
    unmatched = []
    for val in mentioned_values:
        # Skip trivial values (0, 1, 100) and very small numbers
        if val in (0.0, 1.0, 100.0) or val < 0.01:
            continue
        # Check if this value or a close approximation exists in data
        found = False
        for data_val in data_values:
            if abs(val - data_val) < 0.001 or (data_val != 0 and abs((val - data_val) / data_val) < 0.01):
                found = True
                break
        if not found:
            unmatched.append(val)

    if unmatched:
        unmatched_strs = [str(v) for v in sorted(unmatched)[:10]]
        violations.append(
            f"The following numeric values mentioned in the analysis were not found "
            f"in the raw data: {', '.join(unmatched_strs)}. "
            f"These may be inaccurate or fabricated."
        )

    passed = len(violations) == 0
    return {
        "passed": passed,
        "status": "passed" if passed else "failed",
        "violations": violations,
    }


def check_missing_citations(section_content: str, citation_keys: list[str]) -> dict:
    r"""Check if section content references citations not in the provided citation_keys list.

    Looks for patterns like \cite{key}, @key, [N] patterns in content.
    Returns dict with status and list of missing citation references.
    """
    violations = []

    if not section_content or not section_content.strip():
        return {"status": "passed", "violations": []}

    # Find \cite{key} patterns
    cite_pattern = re.compile(r"\\cite\{([^}]+)\}")
    found_cite_keys = set()
    for match in cite_pattern.finditer(section_content):
        keys = [k.strip() for k in match.group(1).split(",")]
        found_cite_keys.update(keys)

    # Find @key patterns (common in markdown)
    at_pattern = re.compile(r"@(\w+)")
    for match in at_pattern.finditer(section_content):
        found_cite_keys.add(match.group(1))

    # Check against provided keys
    available_keys = set(citation_keys) if citation_keys else set()
    missing = found_cite_keys - available_keys

    if missing:
        for key in sorted(missing):
            violations.append(f"Citation key '{key}' referenced in content but not found in citation list")

    status = "failed" if violations else "passed"
    return {"status": status, "violations": violations}


def generate_ai_disclosure(disclosure_type: str = "standard") -> str:
    """Generate an AI usage disclosure statement.

    Args:
        disclosure_type: "standard", "minimal", or "detailed"

    Returns:
        Disclosure text string.
    """
    disclosures = {
        "minimal": (
            "This work was prepared with AI-assisted writing tools. "
            "All content has been reviewed and verified by the authors."
        ),
        "standard": (
            "This manuscript was prepared with AI-assisted tools for literature analysis, "
            "idea generation, and drafting support. All content has been reviewed and verified "
            "by the authors. The AI tools used are acknowledged as writing aids and are not "
            "listed as authors. All experimental results presented are based on actual data "
            "and have not been fabricated. All citations have been verified by the authors."
        ),
        "detailed": (
            "Disclosure of AI-Assisted Tools Usage\n\n"
            "1. Literature Analysis: AI tools were used to analyze and summarize research papers, "
            "extract key findings, and identify research gaps. All AI-generated summaries were "
            "reviewed against original sources.\n\n"
            "2. Idea Generation: AI-assisted brainstorming was used to explore potential research "
            "directions. Final research ideas were selected and refined by the authors.\n\n"
            "3. Drafting Support: AI tools provided initial draft text for certain sections. "
            "All drafted content was substantially revised, fact-checked, and approved by the authors.\n\n"
            "4. Experimental Results: All experimental results presented in this manuscript are "
            "based on actual data collected and analyzed by the authors. No results were fabricated "
            "or generated by AI tools.\n\n"
            "5. Citations: All references cited in this manuscript have been verified by the authors. "
            "No references were fabricated or hallucinated by AI tools.\n\n"
            "The authors take full responsibility for the content, accuracy, and integrity of this manuscript."
        ),
    }

    return disclosures.get(disclosure_type, disclosures["standard"])
