"""mvp2_new_models

Revision ID: 4d90f5847f42
Revises: b4beb57eeb4c
Create Date: 2026-06-12 11:00:14.008549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d90f5847f42'
down_revision: Union[str, None] = 'b4beb57eeb4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_role', sa.String(length=100), nullable=True),
    sa.Column('expertise_area', sa.String(length=255), nullable=True),
    sa.Column('overall_assessment', sa.Text(), nullable=True),
    sa.Column('novelty_concerns', sa.JSON(), nullable=True),
    sa.Column('method_concerns', sa.JSON(), nullable=True),
    sa.Column('experiment_concerns', sa.JSON(), nullable=True),
    sa.Column('writing_concerns', sa.JSON(), nullable=True),
    sa.Column('major_issues', sa.JSON(), nullable=True),
    sa.Column('minor_issues', sa.JSON(), nullable=True),
    sa.Column('suggested_experiments', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewer_simulations_id'), 'reviewer_simulations', ['id'], unique=False)
    op.create_table('method_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_changes', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('based_on_idea_id', sa.Integer(), nullable=True),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['based_on_idea_id'], ['research_ideas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['method_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_method_versions_id'), 'method_versions', ['id'], unique=False)
    op.create_table('paper_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('chunk_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_chunks_id'), 'paper_chunks', ['id'], unique=False)
    op.create_table('evidence_spans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_card_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_section', sa.String(length=500), nullable=True),
    sa.Column('source_text_span', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['paper_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_card_id'], ['paper_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_spans_id'), 'evidence_spans', ['id'], unique=False)
    op.create_table('experiment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('method_version_id', sa.Integer(), nullable=False),
    sa.Column('experiment_plan_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('experiment_type', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('upload_format', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['experiment_plan_id'], ['experiment_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['method_version_id'], ['method_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_results_id'), 'experiment_results', ['id'], unique=False)
    op.create_table('manuscript_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manuscript_state_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('method_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_state_id'], ['manuscript_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['method_version_id'], ['method_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscript_sections_id'), 'manuscript_sections', ['id'], unique=False)
    op.create_table('results_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_result_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('comparison_table', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('statistical_notes', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('compliance_status', sa.String(length=50), nullable=True),
    sa.Column('compliance_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['experiment_result_id'], ['experiment_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_result_id')
    )
    op.create_index(op.f('ix_results_analyses_id'), 'results_analyses', ['id'], unique=False)
    op.add_column('manuscript_states', sa.Column('active_method_version_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('manuscript_states') as batch_op:
        batch_op.create_foreign_key('fk_manuscript_states_active_method_version_id', 'method_versions', ['active_method_version_id'], ['id'], ondelete='SET NULL')
    op.add_column('papers', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('papers', sa.Column('pdf_parse_status', sa.String(length=50), nullable=True))
    op.add_column('research_ideas', sa.Column('differentiation_check', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_ideas', 'differentiation_check')
    op.drop_column('papers', 'pdf_parse_status')
    op.drop_column('papers', 'chunk_count')
    with op.batch_alter_table('manuscript_states') as batch_op:
        batch_op.drop_constraint('fk_manuscript_states_active_method_version_id', type_='foreignkey')
    op.drop_column('manuscript_states', 'active_method_version_id')
    op.drop_index(op.f('ix_results_analyses_id'), table_name='results_analyses')
    op.drop_table('results_analyses')
    op.drop_index(op.f('ix_manuscript_sections_id'), table_name='manuscript_sections')
    op.drop_table('manuscript_sections')
    op.drop_index(op.f('ix_experiment_results_id'), table_name='experiment_results')
    op.drop_table('experiment_results')
    op.drop_index(op.f('ix_evidence_spans_id'), table_name='evidence_spans')
    op.drop_table('evidence_spans')
    op.drop_index(op.f('ix_paper_chunks_id'), table_name='paper_chunks')
    op.drop_table('paper_chunks')
    op.drop_index(op.f('ix_method_versions_id'), table_name='method_versions')
    op.drop_table('method_versions')
    op.drop_index(op.f('ix_reviewer_simulations_id'), table_name='reviewer_simulations')
    op.drop_table('reviewer_simulations')
    # ### end Alembic commands ###
