"""mvp3_citations_templates_exports

Revision ID: b1a465e159f5
Revises: 4d90f5847f42
Create Date: 2026-06-12 11:43:59.763636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a465e159f5'
down_revision: Union[str, None] = '4d90f5847f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('section_mapping', sa.JSON(), nullable=True),
    sa.Column('style_config', sa.JSON(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_templates_id'), 'export_templates', ['id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cite_key', sa.String(length=100), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('raw_bibtex', sa.Text(), nullable=True),
    sa.Column('extra_fields', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('linked_paper_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['linked_paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_id'), 'citations', ['id'], unique=False)
    op.create_table('export_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('manuscript_state_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('export_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('compilation_log', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manuscript_state_id'], ['manuscript_states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['export_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_records_id'), 'export_records', ['id'], unique=False)
    op.create_table('section_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manuscript_section_id', sa.Integer(), nullable=False),
    sa.Column('citation_id', sa.Integer(), nullable=False),
    sa.Column('citation_context', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manuscript_section_id'], ['manuscript_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_citations_id'), 'section_citations', ['id'], unique=False)
    op.add_column('manuscript_sections', sa.Column('figure_refs', sa.JSON(), nullable=True))
    op.add_column('manuscript_sections', sa.Column('table_refs', sa.JSON(), nullable=True))
    op.add_column('manuscript_sections', sa.Column('equation_refs', sa.JSON(), nullable=True))
    op.add_column('manuscript_sections', sa.Column('citation_keys', sa.JSON(), nullable=True))
    op.add_column('manuscript_sections', sa.Column('generated_content', sa.Text(), nullable=True))
    op.add_column('manuscript_states', sa.Column('export_status', sa.String(length=50), nullable=True))
    op.add_column('manuscript_states', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'manuscript_states', 'export_templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manuscript_states', type_='foreignkey')
    op.drop_column('manuscript_states', 'template_id')
    op.drop_column('manuscript_states', 'export_status')
    op.drop_column('manuscript_sections', 'generated_content')
    op.drop_column('manuscript_sections', 'citation_keys')
    op.drop_column('manuscript_sections', 'equation_refs')
    op.drop_column('manuscript_sections', 'table_refs')
    op.drop_column('manuscript_sections', 'figure_refs')
    op.drop_index(op.f('ix_section_citations_id'), table_name='section_citations')
    op.drop_table('section_citations')
    op.drop_index(op.f('ix_export_records_id'), table_name='export_records')
    op.drop_table('export_records')
    op.drop_index(op.f('ix_citations_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_export_templates_id'), table_name='export_templates')
    op.drop_table('export_templates')
    # ### end Alembic commands ###
