"""initial

Revision ID: b4beb57eeb4c
Revises: 
Create Date: 2026-06-12 10:20:10.137491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4beb57eeb4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_field', sa.String(length=255), nullable=True),
    sa.Column('target_venue', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('manuscript_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('contributions', sa.JSON(), nullable=True),
    sa.Column('outline', sa.JSON(), nullable=True),
    sa.Column('current_draft', sa.Text(), nullable=True),
    sa.Column('compliance_status', sa.String(length=50), nullable=True),
    sa.Column('compliance_details', sa.JSON(), nullable=True),
    sa.Column('method_version', sa.Integer(), nullable=False),
    sa.Column('unresolved_issues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscript_states_id'), 'manuscript_states', ['id'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'parsing', 'parsed', 'analyzing', 'analyzed', 'error', name='paperstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_id'), 'papers', ['id'], unique=False)
    op.create_table('research_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('research_gap', sa.Text(), nullable=True),
    sa.Column('proposed_solution', sa.Text(), nullable=True),
    sa.Column('related_papers', sa.JSON(), nullable=True),
    sa.Column('expected_contributions', sa.JSON(), nullable=True),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('feasibility_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('experiment_plan_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_ideas_id'), 'research_ideas', ['id'], unique=False)
    op.create_table('experiment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('main_experiments', sa.JSON(), nullable=True),
    sa.Column('ablation_studies', sa.JSON(), nullable=True),
    sa.Column('robustness_tests', sa.JSON(), nullable=True),
    sa.Column('efficiency_tests', sa.JSON(), nullable=True),
    sa.Column('datasets', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('baselines', sa.JSON(), nullable=True),
    sa.Column('risk_and_fallbacks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['research_ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_id')
    )
    op.create_index(op.f('ix_experiment_plans_id'), 'experiment_plans', ['id'], unique=False)
    op.create_table('paper_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('research_problem', sa.Text(), nullable=True),
    sa.Column('method_summary', sa.Text(), nullable=True),
    sa.Column('novelty_points', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=True),
    sa.Column('datasets', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('baselines', sa.JSON(), nullable=True),
    sa.Column('main_results', sa.JSON(), nullable=True),
    sa.Column('reproducibility', sa.Text(), nullable=True),
    sa.Column('evidence_spans', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id')
    )
    op.create_index(op.f('ix_paper_cards_id'), 'paper_cards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_cards_id'), table_name='paper_cards')
    op.drop_table('paper_cards')
    op.drop_index(op.f('ix_experiment_plans_id'), table_name='experiment_plans')
    op.drop_table('experiment_plans')
    op.drop_index(op.f('ix_research_ideas_id'), table_name='research_ideas')
    op.drop_table('research_ideas')
    op.drop_index(op.f('ix_papers_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_manuscript_states_id'), table_name='manuscript_states')
    op.drop_table('manuscript_states')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
